version: '3.8'
services:
  node14:
    build:
      context: .docker
      dockerfile: node14.Dockerfile

  ticket-booking:
    image: 'ticket-booking_node14'
    container_name: ticket-booking
    depends_on:
      - mysqldb_ticket
      - node14
    volumes:
      - './:/var/www/app'
    restart: always
    networks:
      booksys:
        ipv4_address: 172.32.0.2
        aliases:
          - ticket-booking.local
    command: >
      bash -c "npm install
      && npm run dev"

  postgresdb:
    container_name: postgresdb
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - postgresdb:/var/lib/postgresql/data
      - ./db/postgress.sql:/docker-entrypoint-initdb.d/postgress.sql
    networks:
     booksys:
        ipv4_address: 172.32.0.3
        aliases:
          - postgresdb.local

  mysqldb_ticket:
    container_name: mysqldb_ticket
    restart: always
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - 'mysqldb_ticket:/var/lib/mysql'
    ports:
      - '3306:3306'
      - '2206:22'
    networks:
     booksys:
        ipv4_address: 172.32.0.4
        aliases:
          - mysqldb_ticket.local


volumes:
  postgresdb:
    driver: local
  mysqldb_ticket:




networks:
  booksys:
    ipam:
      driver: default
      config:
        - subnet: 172.32.0.0/24